
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marddium/public_html/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -name "*.html" -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type f -name "*.css" -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type f -name "*.js" -exec chmod 644 {} \;
