---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marddium/public_html
    - export REPOPATH=/home/marddium/repositories/stellar-seo-website-design
    - echo "🚀 Starting deployment from $REPOPATH to $DEPLOYPATH"
    - echo "🔧 PRE-DEPLOYMENT: Working from repository directory..."
    - cd $REPOPATH
    - pwd
    - echo "📊 Git status before cleanup:"
    - git status
    - echo "🧹 Stashing any local changes..."
    - git stash push -u -m "Auto-stash before deployment $(date)" || true
    - echo "🔄 Ensuring we're on main branch..."
    - git checkout main
    - echo "⬇️ Fetching latest from GitHub..."
    - git fetch origin main
    - echo "🔨 Hard reset to match GitHub exactly..."
    - git reset --hard origin/main
    - echo "🧽 Cleaning any remaining untracked files..."
    - git clean -fd
    - echo "✅ Repository sync completed!"
    - echo "📋 Current commit after reset:"
    - git log --oneline -1
    - echo "📁 Checking dist folder exists and has content:"
    - ls -la $REPOPATH/dist/ || echo "⚠️ dist folder not found!"
    - echo "🗂️ Checking what's currently in web directory:"
    - ls -la $DEPLOYPATH/
    - echo "🚀 Copying files from $REPOPATH/dist/ to $DEPLOYPATH/"
    - /bin/cp -R $REPOPATH/dist/* $DEPLOYPATH/
    - echo "🔐 Setting proper permissions..."
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \; 2>/dev/null || true
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \; 2>/dev/null || true
    - echo "✅ Verifying critical files deployed:"
    - ls -la $DEPLOYPATH/index.html || echo "❌ index.html missing!"
    - ls -la $DEPLOYPATH/sitemap.xml || echo "❌ sitemap.xml missing!"
    - ls -la $DEPLOYPATH/robots.txt || echo "❌ robots.txt missing!"
    - echo "🎉 Deployment completed successfully!"
    - echo "🌐 Website should be live at https://mardenseo.com"
    - echo "🕐 Deployment time: $(date)"