---
deployment:
  tasks:
    # Set up logging and detect current setup
    - export LOGFILE=/home/marddium/deployment-debug.log
    - echo "=== HYBRID DEPLOYMENT $(date) ===" > $LOGFILE
    
    # Detect which setup we're in
    - export CURRENT_DIR=$(pwd)
    - echo "Current directory: $CURRENT_DIR" | tee -a $LOGFILE
    
    # Set deployment variables based on detected setup
    - if [[ "$CURRENT_DIR" == *"public_html"* ]]; then export DEPLOY_MODE="direct"; export DEPLOYPATH="$CURRENT_DIR"; else export DEPLOY_MODE="copy"; export DEPLOYPATH="/home/marddium/public_html"; fi
    - echo "Deploy mode: $DEPLOY_MODE" | tee -a $LOGFILE
    - echo "Deploy path: $DEPLOYPATH" | tee -a $LOGFILE
    
    # System info
    - whoami | tee -a $LOGFILE
    - node --version 2>&1 | tee -a $LOGFILE || echo "❌ Node.js not available" | tee -a $LOGFILE
    - npm --version 2>&1 | tee -a $LOGFILE || echo "❌ NPM not available" | tee -a $LOGFILE
    
    # Install and build if package.json exists
    - if test -f package.json; then echo "📦 Installing dependencies..." | tee -a $LOGFILE && npm install 2>&1 | tee -a $LOGFILE; fi
    - if test -f package.json; then echo "🏗️ Building project..." | tee -a $LOGFILE && npm run build 2>&1 | tee -a $LOGFILE; fi
    
    # Deploy based on mode
    - if [ "$DEPLOY_MODE" = "direct" ]; then echo "📁 Direct deployment - moving files..." | tee -a $LOGFILE && if test -d dist; then cp -R dist/* . 2>&1 | tee -a $LOGFILE; fi; else echo "📋 Copy deployment..." | tee -a $LOGFILE && if test -d dist; then cp -R dist/* $DEPLOYPATH/ 2>&1 | tee -a $LOGFILE; fi; fi
    
    # Clean up if direct mode
    - if [ "$DEPLOY_MODE" = "direct" ]; then echo "🧹 Cleaning development files..." | tee -a $LOGFILE && rm -rf src/ node_modules/ dist/ *.md package*.json *.config.* .git* .env* 2>&1 | tee -a $LOGFILE || true; fi
    
    # Set permissions
    - echo "🔐 Setting permissions..." | tee -a $LOGFILE
    - find $DEPLOYPATH -type d -exec chmod 755 {} \; 2>&1 | tee -a $LOGFILE || true
    - find $DEPLOYPATH -type f -exec chmod 644 {} \; 2>&1 | tee -a $LOGFILE || true
    
    # Verify deployment
    - echo "✅ Verifying deployment..." | tee -a $LOGFILE
    - test -f $DEPLOYPATH/index.html && echo "✅ index.html deployed" | tee -a $LOGFILE || echo "❌ index.html missing" | tee -a $LOGFILE
    - ls -la $DEPLOYPATH/ | head -10 | tee -a $LOGFILE
    
    # Final status
    - echo "🎉 Hybrid deployment completed in $DEPLOY_MODE mode!" | tee -a $LOGFILE