---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marddium/public_html/
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;