---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marddium/public_html/
    - echo "🚀 Starting deployment to $DEPLOYPATH"
    - echo "🔧 PRE-DEPLOYMENT: Resolving Git conflicts..."
    - pwd
    - echo "📊 Git status before cleanup:"
    - git status
    - echo "🧹 Stashing any local changes (including .htaccess conflicts)..."
    - git stash push -u -m "Auto-stash before deployment $(date)"
    - echo "🔄 Ensuring we're on main branch..."
    - git checkout main
    - echo "⬇️ Fetching latest from GitHub..."
    - git fetch origin main
    - echo "🔨 Hard reset to match GitHub exactly..."
    - git reset --hard origin/main
    - echo "🧽 Cleaning any remaining untracked files..."
    - git clean -fd
    - echo "✅ Repository sync completed!"
    - echo "📋 Current commit after reset:"
    - git log --oneline -1
    - echo "📁 Listing dist folder contents:"
    - ls -la dist/
    - echo "🚀 Copying files from dist/ to $DEPLOYPATH"
    - /bin/cp -R dist/* $DEPLOYPATH/
    - echo "🔐 Setting proper permissions..."
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - echo "✅ Verifying critical files deployed:"
    - ls -la $DEPLOYPATH/index.html
    - ls -la $DEPLOYPATH/sitemap.xml
    - ls -la $DEPLOYPATH/robots.txt
    - ls -la $DEPLOYPATH/.htaccess
    - echo "🎉 Deployment completed successfully!"
    - echo "🌐 Website should be live at https://mardenseo.com"