---
deployment:
  tasks:
    # Step 1: Set up environment variables
    - export DEPLOYPATH=/home/marddium/public_html/
    - export NODE_VERSION=18
    - export PATH=/opt/cpanel/ea-nodejs${NODE_VERSION}/bin:$PATH
    
    # Step 2: Install Node.js and npm (if not available)
    - command -v node || curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
    - command -v npm || yum install -y npm
    
    # Step 3: Install project dependencies
    - echo "Installing dependencies..."
    - npm install --production=false
    
    # Step 4: Build the React project
    - echo "Building Marden SEO project..."
    - npm run build
    
    # Step 5: Verify build output
    - echo "Verifying build output..."
    - test -d dist && echo "✅ Build directory exists" || (echo "❌ Build failed - no dist directory" && exit 1)
    - test -f dist/index.html && echo "✅ index.html found" || (echo "❌ index.html missing" && exit 1)
    - test -f dist/sitemap.xml && echo "✅ sitemap.xml found" || echo "⚠️ sitemap.xml missing"
    - test -f dist/robots.txt && echo "✅ robots.txt found" || echo "⚠️ robots.txt missing"
    
    # Step 6: Clean deployment directory (safely)
    - echo "Preparing deployment directory..."
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/find $DEPLOYPATH -mindepth 1 -not -name '.well-known' -not -name 'cgi-bin' -delete
    
    # Step 7: Copy built files to public_html
    - echo "Deploying files..."
    - /bin/cp -R dist/* $DEPLOYPATH/
    
    # Step 8: Set proper file permissions
    - echo "Setting file permissions..."
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    
    # Step 9: Create/update .htaccess for React Router and SEO
    - echo "Configuring .htaccess..."
    - |
      cat > $DEPLOYPATH/.htaccess << 'EOF'
      # React Router SPA Configuration
      RewriteEngine On
      RewriteRule ^(?!.*\.).*$ /index.html [L]
      
      # SEO Headers
      <Files "sitemap.xml">
          Header set Content-Type "application/xml; charset=utf-8"
      </Files>
      
      <Files "robots.txt">
          Header set Content-Type "text/plain; charset=utf-8"
      </Files>
      
      # Security Headers
      <IfModule mod_headers.c>
          Header always set X-Frame-Options "SAMEORIGIN"
          Header always set X-Content-Type-Options "nosniff"
      </IfModule>
      
      # Cache Control for Performance
      <FilesMatch "\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$">
          Header set Cache-Control "max-age=31536000, public"
      </FilesMatch>
      
      # GZIP Compression
      <IfModule mod_deflate.c>
          AddOutputFilterByType DEFLATE text/plain text/html text/xml text/css application/xml application/javascript application/x-javascript
      </IfModule>
      EOF
    
    # Step 10: Set .htaccess permissions
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    
    # Step 11: Verify deployment
    - echo "Verifying deployment..."
    - /bin/ls -la $DEPLOYPATH/index.html $DEPLOYPATH/sitemap.xml $DEPLOYPATH/robots.txt
    - echo "🎉 Marden SEO deployment completed successfully!"
    - echo "🌐 Site: https://mardenseo.com"
    - echo "🗺️ Sitemap: https://mardenseo.com/sitemap.xml"