---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marddium/public_html/
    - echo "🚀 Starting deployment to $DEPLOYPATH"
    - echo "🔧 Resolving any Git conflicts..."
    - git config --global user.email "deploy@mardenseo.com"
    - git config --global user.name "cPanel Deploy Bot"
    - echo "🔄 Resetting repository to clean state..."
    - git fetch origin
    - git reset --hard origin/main
    - echo "✅ Repository reset completed"
    - echo "📁 Listing dist folder contents:"
    - ls -la dist/
    - echo "📋 Current deployment commit:"
    - git log --oneline -1
    - echo "🚀 Copying files from dist/ to $DEPLOYPATH"
    - /bin/cp -R dist/* $DEPLOYPATH/
    - echo "🔐 Setting proper permissions..."
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - echo "✅ Verifying critical files deployed:"
    - ls -la $DEPLOYPATH/index.html
    - ls -la $DEPLOYPATH/sitemap.xml
    - ls -la $DEPLOYPATH/robots.txt
    - ls -la $DEPLOYPATH/.htaccess
    - echo "🎉 Deployment completed successfully!"
    - echo "🌐 Website should be live at https://mardenseo.com"