---
deployment:
  tasks:
    # Set up variables and logging
    - export DEPLOYPATH=/home/marddium/public_html
    - export REPOPATH=/home/marddium/repositories/stellar-seo-website-design
    - export LOGFILE=/home/marddium/deployment-debug.log
    - echo "=== SIMPLE DEPLOYMENT TEST $(date) ===" > $LOGFILE
    
    # Test basic system info
    - echo "🔍 SYSTEM INFO:" | tee -a $LOGFILE
    - whoami | tee -a $LOGFILE
    - pwd | tee -a $LOGFILE
    - echo "Node version test:" | tee -a $LOGFILE
    - node --version 2>&1 | tee -a $LOGFILE || echo "❌ Node.js not found" | tee -a $LOGFILE
    - echo "NPM version test:" | tee -a $LOGFILE  
    - npm --version 2>&1 | tee -a $LOGFILE || echo "❌ NPM not found" | tee -a $LOGFILE
    
    # Repository sync
    - echo "🔧 REPOSITORY SYNC:" | tee -a $LOGFILE
    - cd $REPOPATH || (echo "❌ FATAL: Cannot access repository" | tee -a $LOGFILE && exit 1)
    - git fetch origin main 2>&1 | tee -a $LOGFILE
    - git reset --hard origin/main 2>&1 | tee -a $LOGFILE
    - echo "Current commit:" | tee -a $LOGFILE
    - git log --oneline -1 2>&1 | tee -a $LOGFILE
    
    # Check if dist exists in repo
    - echo "📁 CHECKING DIST FOLDER:" | tee -a $LOGFILE
    - test -d $REPOPATH/dist && echo "✅ dist folder exists" | tee -a $LOGFILE || echo "❌ dist folder missing" | tee -a $LOGFILE
    - ls -la $REPOPATH/dist/ 2>&1 | tee -a $LOGFILE || echo "Cannot list dist contents" | tee -a $LOGFILE
    
    # Test deployment path
    - echo "🗂️ CHECKING DEPLOYMENT PATH:" | tee -a $LOGFILE
    - test -d $DEPLOYPATH && echo "✅ Deploy path exists" | tee -a $LOGFILE || echo "❌ Deploy path missing" | tee -a $LOGFILE
    - ls -la $DEPLOYPATH/ | tee -a $LOGFILE
    
    # Create a test file to verify deployment works
    - echo "🧪 TESTING DEPLOYMENT:" | tee -a $LOGFILE
    - echo "DEPLOYMENT TEST $(date)" > /tmp/deployment-test.txt
    - cp /tmp/deployment-test.txt $DEPLOYPATH/deployment-test.txt 2>&1 | tee -a $LOGFILE
    - test -f $DEPLOYPATH/deployment-test.txt && echo "✅ Test file deployed successfully" | tee -a $LOGFILE || echo "❌ Test file deployment failed" | tee -a $LOGFILE
    
    # IF dist exists, copy it
    - echo "📋 CONDITIONAL DIST COPY:" | tee -a $LOGFILE
    - if test -d $REPOPATH/dist; then echo "Copying existing dist folder..." | tee -a $LOGFILE && cp -R $REPOPATH/dist/* $DEPLOYPATH/ 2>&1 | tee -a $LOGFILE; else echo "No dist folder to copy, skipping..." | tee -a $LOGFILE; fi
    
    # Final verification
    - echo "✅ FINAL CHECK:" | tee -a $LOGFILE
    - ls -la $DEPLOYPATH/ | tee -a $LOGFILE
    - echo "🎉 Simple deployment test completed!" | tee -a $LOGFILE