// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhwhdokmdqpwtgipivwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVod2hkb2ttZHFwd3RnaXBpdndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTMxNjUsImV4cCI6MjA1OTcyOTE2NX0.ckVXi3ny0PJs4eBoq_xEU8KNPo0jPYaeCBfaMQiACUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);